### ISSUE TITLE
Add speech-to-point functionality

### ISSUE THREAD

**Issue by dmarulli** [Streets-Data-Collaborative/geo-street-talk-global#12]

**Comment by YukunVVan** [comment]
David, is this issue the same thing as inverse_Streettalk()? So actually we have three things to do: inverse_Streettalk(), easy-to-use package and API-ify, right?

**Comment by vr00n** [comment]
To state the use case more clearly:

1. Mayne hails an AV running GST
2. Mayne enters the AV running GST
3. Mayne says `Take me to 23rd between 6th and 7th avenue`
4. GST detects `Take me to 23rd between 6th and 7th avenue` and computes:
   - OnStreet = 23rd
   - FromStreet = 6th
   - ToStreet = 7th
5. GST searches for street segment that matches "23rd,6,7" and returns the top-matched street_segment.
6. GST calculates the mid-point for the top matched street_segment.
7. AV sets destination = GST output.

**Comment by dmarulli** [comment]
@YukunVVan  - This was actually a duplicate issue. Sorry about that. Please see issues #8 and #10.

For clarity though: my thinking is that `inverse_streetTalk()` is basically only useful in the realtime API case. The intuition here is that while enriching datasets of lat/lng pairs with human-readable strings is useful whether or not one does it in realtime, receiving human-readable strings and outputting lat/lng pairs isn't really. So we don't have to package `inverse_streetTalk()` into the "static" python module.

To add to @vr00n 's use case sketch, technically speaking (at least as I have initially conceived things) the `speech_to_point()` function would:
- receive an audio file as a input
- convert that speech to text
- feed that text to `inverse_streetTalk()`
- return a point (presumably to be fed into some routing software)
