### ISSUE TITLE
Tie a ribbon around the current work by creating easy-to-use package (02/21/18)

### ISSUE THREAD

**Issue by dmarulli** [Streets-Data-Collaborative/geo-street-talk-global#9]
As we have discussed, my thinking here is the first stable point before fully API-ifying this work is to simply clean up what we have here by adding a few conventional pieces to make the repo a package for other developers to enrich spatial data with.

This may be a helpful reference: https://python-packaging.readthedocs.io/en/latest/

(I have created a separate project to track the API work--we may want to create a separate repo instead, but we can cross that bridge after doing a little more research.)

**Comment by patwater** [comment]
Great points @dmarulli and sounds like a prudent path ahead. CC @YukunVVan

**Comment by YukunVVan** [comment]
Hey! I have created python package named 'geo_street_talk' and already uploaded to [PyPI](https://pypi.python.org/pypi/geo-street-talk/0.1.2.1). It can be installed via `pip install geo_street_talk`. 
It needs around 11 mins to search a Point if the user has not downloaded the Open street map before.
Please advise what kind of document/guideline should be added. Thx!!

**Comment by dmarulli** [comment]
Awesome stuff @YukunVVan.

I'll think about what we may want to include in an updated README. 

Re: documentation, I believe we can use [readthedocs](http://docs.readthedocs.io/en/latest/index.html) to programmatically generate documentation and host it for the open source community.

**Comment by patwater** [comment]
+1 on readthedocs @YukunVVan

**Comment by YukunVVan** [comment]
I have created docs with Sphinx and already pushed them in github. However, it seems that I need to connect the readthedocs account with this github account in order to build the docs successfully. It shows that 

> "This repository doesn't have a valid webhook set up, commits won't trigger new builds for this project." 

Do you know how to solve this? Thx.
@dmarulli @patwater @vr00n

**Comment by dmarulli** [comment]
<img width="1280" alt="screen shot 2018-03-08 at 12 16 35 pm" src="https://user-images.githubusercontent.com/9664173/37174151-97bca750-22ca-11e8-89d6-61235df49447.png">

@YukunVVan - I have added a readthedocs integration. There's another option to add a custom webhook if this doesn't work.

**Comment by patwater** [comment]
@YukunVVan does that address your issue?

**Comment by YukunVVan** [comment]
Thanks! It works now. @dmarulli @patwater 
[http://geo-street-talk.readthedocs.io/](http://geo-street-talk.readthedocs.io/)

**Comment by dmarulli** [comment]
Nice! Very cool @YukunVVan . Closing.
